language: node_js
node_js: "8.10.0"

install:
  - go get google.golang.org/grpc

before_script:
  - cd $GOPATH/src/google.golang.org/grpc/examples/route_guide && go run server/server.go &
  - go version
  - node --version

script:
  - cd $HOME/build/Stoakes/unplugrpc/gateway && npm install
  - npm run build
  - npm start &
  - npm run lint
  - npm run test
  - cd ../ui
  - yarn install
  - npm run lint
  - npm run test

after_script:
  - pkill go
